apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocktop-infer
  labels:
    app: rocktop-infer
    owner: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocktop-infer
  template:
    metadata:
      labels:
        app: rocktop-infer
        owner: dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: infer
          image: ghcr.io/example/rocktop:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
