name: Actionlint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  actionlint:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@v1
