name: Release Images and SBOMs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  discover:
    name: Discover Dockerfiles
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count: ${{ steps.set-matrix.outputs.count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t files < <(git ls-files 'Dockerfile' 'docker/**/Dockerfile*' '**/Dockerfile' || true)
          if [ ${#files[@]} -eq 0 ]; then
            echo "matrix={\"include\":[]}" >> "$GITHUB_OUTPUT"
            echo "count=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          printf '{"include":[' > matrix.json
          first=1
          for f in "${files[@]}"; do
            ctx=$(dirname "$f")
            [ "$ctx" = "." ] && ctx="."
            base=$(basename "$f")
            suf=${base#Dockerfile}
            if [ -z "$suf" ]; then suf="base"; else suf=${suf#.}; fi
            [ $first -eq 0 ] && printf ',' >> matrix.json || first=0
            printf '{"context":"%s","file":"%s","image_suffix":"%s"}' "$ctx" "$f" "$suf" >> matrix.json
          done
          printf ']}' >> matrix.json
          echo "matrix=$(cat matrix.json)" >> "$GITHUB_OUTPUT"
          echo "count=${#files[@]}" >> "$GITHUB_OUTPUT"

  build-push-sign:
    name: Build, push, sign, attest images
    runs-on: ubuntu-24.04
    needs: discover
    if: ${{ needs.discover.outputs.count != '0' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},prefix=${{ matrix.image_suffix }}-
            type=raw,value=${{ matrix.image_suffix }}-latest

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Pick primary tag
        id: imagename
        shell: bash
        run: |
          first_tag=$(printf "%s\n" "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "tag=$first_tag" >> "$GITHUB_OUTPUT"

      - name: Syft SBOM (image SPDX)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.imagename.outputs.tag }}
          artifact-name: release-sbom-image-${{ matrix.image_suffix }}.spdx.json
          output-file: release-sbom-image-${{ matrix.image_suffix }}.spdx.json
          format: spdx-json

      - name: Syft SBOM (image CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.imagename.outputs.tag }}
          artifact-name: release-sbom-image-${{ matrix.image_suffix }}.cdx.json
          output-file: release-sbom-image-${{ matrix.image_suffix }}.cdx.json
          format: cyclonedx-json

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: ${{ steps.imagename.outputs.tag }}
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Cosign sign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes ${{ steps.imagename.outputs.tag }}

      - name: Cosign attest (SPDX)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign attest --yes \
            --type spdxjson \
            --predicate release-sbom-image-${{ matrix.image_suffix }}.spdx.json \
            ${{ steps.imagename.outputs.tag }}

      - name: Cosign attest (CycloneDX)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign attest --yes \
            --type cyclonedx \
            --predicate release-sbom-image-${{ matrix.image_suffix }}.cdx.json \
            ${{ steps.imagename.outputs.tag }}

  release-assets:
    name: Publish repo SBOMs to release
    runs-on: ubuntu-24.04
    needs: [discover, build-push-sign]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate repo SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: release-sbom-repo.spdx.json
          format: spdx-json
          artifact-name: release-sbom-repo.spdx.json

      - name: Generate repo SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: release-sbom-repo.cdx.json
          format: cyclonedx-json
          artifact-name: release-sbom-repo.cdx.json

      - name: Attach SBOMs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-sbom-repo.spdx.json
            release-sbom-repo.cdx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
