name: Tests

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        python: ['3.11']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v2

      - name: Sync dev environment
        run: |
          uv python install ${{ matrix.python }}
          uv sync --all-extras --dev

      - name: Run pytest wrapper (skip if none)
        run: uv run python scripts/pytest_wrapper.py
