name: Trivy FS Scan

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  trivy-fs:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy filesystem scan (repo)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
